### ISSUE TITLE
[visualization] if not all json files are generated, none of them are loaded in html

### ISSUE THREAD

**Issue by Tuo-ZHANG** [Garrafao/WUGs#13]
the stats_agreement.json is not generated when viewing graph in the discowug_unc dataset, and it leads to all statistics not rendering

**Comment by lukasMI** [comment]
Because JavaScript can run asynchronously, the issue was that the script tried to fill statistics before resolving all the JSON data, which caused all statistics to be empty instead of just the ones from missing JSON files. Now, when loading in the JSON data, it first resolves and fully loads the data or says it can't be found, and then it only executes code based on whether a specific JSON file is loaded.
