### ISSUE TITLE
there are repeated rows in the uses_all.csv in output of one_for_all notebook

### ISSUE THREAD

**Issue by Tuo-ZHANG** [Garrafao/WUGs#23]

**Comment by choppa98** [comment]
So there were duplicates in Russian datasets due to dataset name which has been resolved. There are no more duplicates in the uses. However, there are duplicates in judgments for certain datasets (cosimlex-96, DURel- 3, discowug- 2, diawug - 3, Rudsi -1). These duplicates exist in source as well for DURel, discowug, diawug and Rudsi. Cosimlex still needs to verified.

**Comment by Garrafao** [comment]
@Tuo-ZHANG That basically means that we did not observe duplicates outside of the Russian data sets. I remember you observed it for English data sets. Could you please paste some examples here?

**Comment by Garrafao** [comment]
Closed as not observed in code in this repository (see above). Handled otherwise in scripts outside of this repository according to @Tuo-ZHANG .
